### ISSUE TITLE
Broken link on website

### ISSUE THREAD

**Issue by sanjsanj** [styleguidist/site#7]
On this page https://react-styleguidist.js.org/docs/development.html

There is a link to 'Styles' that points to `#styles` but the name of the anchor further down the page is actually `#styles-1`.

I had a quick look at the `.md` and it is correctly labelled `styles` but either that's not accurate or something is happening to rename that because of a reserved word or something like that.

**Comment by sapegin** [comment]
That’s super weird. It would be `styles-1` if there was another header with `styles` text but there is none.

**Comment by sapegin** [comment]
I see this in some other places too — looks like we don’t reset the slugger between different pages.
